### PR TITLE
ARROW-?????: [C++] Fix handling of Substrait output mapping

### PR DESCRIPTION
**Pull request by rtpsw**
This PR includes a fix and a test case for projection with an output mapping for a "compact-join" relation, i.e. one whose output fields are a compact form of the Substrait standard join fields, as is the case for `asof_join`.

### CODE REVIEW

**Comment by rtpsw** [comment]
The PR's logic came out a bit weird in an effort to satisfy Substrait field indexing. In particular, the `"output_mapping" : [6, 7, 8, 9]` entry in the test case was generated using Ibis-Substrait, and corresponds to the appended fields, but this reveals a weird treatment of indices that appears to be originating in Substrait:
- When no output mapping is used, the indices are not mapped and correspond to non-appended fields (numbered 0-5 in the test case).
- When output mapping is used, the indices are mapped and correspond to appended fields (numbered 6-9 in the test case).

So, I'm not sure whether Ibis-Substrait correctly generates the output mapping, but if it does then the current PR's code should be justified.

**Comment by rtpsw** [comment]
cc @westonpace @icexelloss

**Comment by icexelloss** [comment]
Can we give a Jira  for this?

**Comment by icexelloss** [comment]
Also @rtpsw can you please give a more detailed description of what the issue is and how does this PR fix it?

**Comment by rtpsw** [comment]
> Can we give a Jira for this?

The Arrow project has recently moved its issue handling to GitHub, so you probably mean a GitHub issue. However, this is a personal repo, and I'm not sure what the issue policy here is. @westonpace, should an issue be opened on this repo? on the main Arrow repo? or should an existing issue be reopened in this case?

**Comment by icexelloss** [comment]
Actually I think we can reuse ARROW-18417 for this because the first patch doesn't really fix the issue

**Comment by rtpsw** [comment]
> Also @rtpsw can you please give a more detailed description of what the issue is and how does this PR fix it?

Perhaps it's best to start by comparing the `AsOfJoinWithOutputMapping` test case added in this PR to the existing `AsOfJoinDefaultEmit` test case. The former is exactly like the latter except that it adds a `project` relation wrapping the existing `extension_multi` relation. This `project` relation includes an emit message with an output mapping. This output mapping is the feature being covered by the added test case. Without the code change in this PR, the added test case gets a `SIGSEGV` (see gdb session below) due to accessing an out-of-bounds index. This is index 8 from the output mapping `[6, 7, 8, 9]` and the access is to a schema of size 8 with the fields `time, key, value1, value2, time, key, value1, value2`. This schema is a concatenation of two copies of the `asof_join` output schema, the first copy corresponding to the input and the second copy to the output mapping. This behavior originates in how Ibis-Substrait deals with output mappings, as can be seen in [one of its test case](https://github.com/ibis-project/ibis-substrait/blob/b9b9ded8c8fddf45923d6a705194b702ed7cddbf/ibis_substrait/tests/compiler/test_compiler.py#L225-L251).

So, technically, the problem is incompatible indexing in the context of output mapping - in Arrow-Substrait the first copy of the schema is of size 4 due to the compact form (`time, key, value1, value2`) of the `asof_join` output whereas Ibis-Substrait defines a full-form (`time, key, value1, time, key, value2`) for this output. My understanding is that this is why the output mapping produced by Ibis-Substrait is `[6, 7, 8, 9]` and not `[4, 5, 6, 7]`. One alternative for fixing this incompatibility is changing Ibis-Substrait to produce `[4, 5, 6, 7]`, or, more generally, to be aware of the compact-form of `asof_join`. This may well prove to be a clean alternative, but I suspect it will be difficult to reach consensus about such a change in Ibis-Substrait; this is why I opted not to pursue it. A second alternative is fixing Arrow-Substrait to deal with the indexing convention of Ibis-Substrait; this is what this PR is doing (refer to [this explanation](https://github.com/westonpace/arrow/pull/28#issuecomment-1380472587)).

The above-mentioned gdb session:
```
$ gdb --args ./debug/arrow-substrait-substrait-test --gtest_filter=Substrait.AsOfJoinWithOutputMapping
GNU gdb (Ubuntu 12.0.90-0ubuntu1) 12.0.90
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./debug/arrow-substrait-substrait-test...
(gdb) run
Starting program: /mnt/github/westonpace/arrow/cpp/build/debug/debug/arrow-substrait-substrait-test --gtest_filter=Substrait.AsOfJoinWithOutputMapping
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff11ff640 (LWP 38020)]
Running main() from ./googletest/src/gtest_main.cc
Note: Google Test filter = Substrait.AsOfJoinWithOutputMapping
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from Substrait
[ RUN      ] Substrait.AsOfJoinWithOutputMapping
/mnt/github/westonpace/arrow/cpp/src/arrow/type.cc:1509:  Check failed: (i) < (num_fields()) 
/mnt/github/westonpace/arrow/cpp/build/debug/debug/libarrow.so.1000(_ZN5arrow4util7CerrLog14PrintBackTraceEv+0x39)[0x7ffff467be47]
/mnt/github/westonpace/arrow/cpp/build/debug/debug/libarrow.so.1000(_ZN5arrow4util7CerrLogD1Ev+0x5f)[0x7ffff467bdb7]
/mnt/github/westonpace/arrow/cpp/build/debug/debug/libarrow.so.1000(_ZN5arrow4util7CerrLogD0Ev+0x1c)[0x7ffff467bddc]
/mnt/github/westonpace/arrow/cpp/build/debug/debug/libarrow.so.1000(_ZN5arrow4util8ArrowLogD1Ev+0x4b)[0x7ffff467bbdf]
/mnt/github/westonpace/arrow/cpp/build/debug/debug/libarrow.so.1000(_ZNK5arrow6Schema5fieldEi+0x125)[0x7ffff45133b5]
/mnt/github/westonpace/arrow/cpp/build/debug/debug/libarrow_substrait.so.1000(_ZN5arrow6engine11GetEmitInfoERKN9substrait9RelCommonERKSt10shared_ptrINS_6SchemaEE+0x1a5)[0x7ffff70d1790]
/mnt/github/westonpace/arrow/cpp/build/debug/debug/libarrow_substrait.so.1000(_ZN5arrow6engine11ProcessEmitESt8optionalIN9substrait9RelCommonEERKNS0_15DeclarationInfoERKSt10shared_ptrINS_6SchemaEE+0xc5)[0x7ffff70d1a7b]
/mnt/github/westonpace/arrow/cpp/build/debug/debug/libarrow_substrait.so.1000(_ZN5arrow6engine11ProcessEmitIN9substrait10ProjectRelEEENS_6ResultINS0_15DeclarationInfoEEERKT_RKS5_RKSt10shared_ptrINS_6SchemaEE+0x80)[0x7ffff70e1a20]
/mnt/github/westonpace/arrow/cpp/build/debug/debug/libarrow_substrait.so.1000(_ZN5arrow6engine9FromProtoERKN9substrait3RelERKNS0_12ExtensionSetERKNS0_17ConversionOptionsE+0x2c38)[0x7ffff70d5b7e]
/mnt/github/westonpace/arrow/cpp/build/debug/debug/libarrow_substrait.so.1000(+0x32b9cd)[0x7ffff70ff9cd]
/mnt/github/westonpace/arrow/cpp/build/debug/debug/libarrow_substrait.so.1000(_ZN5arrow6engine16DeserializePlansERKNS_6BufferERKSt8functionIFSt10shared_ptrINS_7compute16SinkNodeConsumerEEvEEPKNS0_19ExtensionIdRegistryEPNS0_12ExtensionSetERKNS0_17ConversionOptionsE+0x6d)[0x7ffff70ffee0]
/mnt/github/westonpace/arrow/cpp/build/debug/debug/arrow-substrait-substrait-test(+0x193264)[0x5555556e7264]
/mnt/github/westonpace/arrow/cpp/build/debug/debug/arrow-substrait-substrait-test(+0x1d07d9)[0x5555557247d9]
/mnt/github/westonpace/arrow/cpp/build/debug/debug/arrow-substrait-substrait-test(_ZN7testing8internal35HandleExceptionsInMethodIfSupportedINS_4TestEvEET0_PT_MS4_FS3_vEPKc+0x8f)[0x5555557be1df]
/mnt/github/westonpace/arrow/cpp/build/debug/debug/arrow-substrait-substrait-test(_ZN7testing4Test3RunEv+0xd6)[0x5555557b3686]
/mnt/github/westonpace/arrow/cpp/build/debug/debug/arrow-substrait-substrait-test(_ZN7testing8TestInfo3RunEv+0x155)[0x5555557b3805]
/mnt/github/westonpace/arrow/cpp/build/debug/debug/arrow-substrait-substrait-test(_ZN7testing9TestSuite3RunEv+0xd9)[0x5555557b3db9]
/mnt/github/westonpace/arrow/cpp/build/debug/debug/arrow-substrait-substrait-test(_ZN7testing8internal12UnitTestImpl11RunAllTestsEv+0x53f)[0x5555557b44bf]
/mnt/github/westonpace/arrow/cpp/build/debug/debug/arrow-substrait-substrait-test(_ZN7testing8internal35HandleExceptionsInMethodIfSupportedINS0_12UnitTestImplEbEET0_PT_MS4_FS3_vEPKc+0x87)[0x5555557be7a7]
/mnt/github/westonpace/arrow/cpp/build/debug/debug/arrow-substrait-substrait-test(_ZN7testing8UnitTest3RunEv+0x9c)[0x5555557b38cc]
/mnt/github/westonpace/arrow/cpp/build/debug/debug/arrow-substrait-substrait-test(+0x13aec4)[0x55555568eec4]
/lib/x86_64-linux-gnu/libc.so.6(+0x29d90)[0x7ffff27e0d90]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80)[0x7ffff27e0e40]
/mnt/github/westonpace/arrow/cpp/build/debug/debug/arrow-substrait-substrait-test(+0x13b505)[0x55555568f505]

Thread 1 "arrow-substrait" received signal SIGABRT, Aborted.
__pthread_kill_implementation (no_tid=0, signo=6, threadid=140737352196544) at ./nptl/pthread_kill.c:44
44	./nptl/pthread_kill.c: No such file or directory.
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140737352196544) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140737352196544) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140737352196544, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff27f9476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff27df7f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007ffff467bdbc in arrow::util::CerrLog::~CerrLog (this=0x5555559fd200, __in_chrg=<optimized out>) at /mnt/github/westonpace/arrow/cpp/src/arrow/util/logging.cc:72
#6  0x00007ffff467bddc in arrow::util::CerrLog::~CerrLog (this=0x5555559fd200, __in_chrg=<optimized out>) at /mnt/github/westonpace/arrow/cpp/src/arrow/util/logging.cc:74
#7  0x00007ffff467bbdf in arrow::util::ArrowLog::~ArrowLog (this=0x7fffffffbf90, __in_chrg=<optimized out>) at /mnt/github/westonpace/arrow/cpp/src/arrow/util/logging.cc:250
#8  0x00007ffff45133b5 in arrow::Schema::field (this=0x5555559fd2b0, i=6) at /mnt/github/westonpace/arrow/cpp/src/arrow/type.cc:1509
#9  0x00007ffff70d1790 in arrow::engine::GetEmitInfo (rel_common=..., input_schema=std::shared_ptr<arrow::Schema> (use count 3, weak count 0) = {...})
    at /mnt/github/westonpace/arrow/cpp/src/arrow/engine/substrait/relation_internal.cc:61
#10 0x00007ffff70d1a7b in arrow::engine::ProcessEmit (rel_common_opt=std::optional<substrait::RelCommon> = {...}, no_emit_declr=..., 
    schema=std::shared_ptr<arrow::Schema> (use count 3, weak count 0) = {...}) at /mnt/github/westonpace/arrow/cpp/src/arrow/engine/substrait/relation_internal.cc:76
#11 0x00007ffff70e1a20 in arrow::engine::ProcessEmit<substrait::ProjectRel> (rel=..., no_emit_declr=..., schema=std::shared_ptr<arrow::Schema> (use count 3, weak count 0) = {...})
    at /mnt/github/westonpace/arrow/cpp/src/arrow/engine/substrait/relation_internal.cc:97
#12 0x00007ffff70d5b7e in arrow::engine::FromProto (rel=..., ext_set=..., conversion_options=...) at /mnt/github/westonpace/arrow/cpp/src/arrow/engine/substrait/relation_internal.cc:508
#13 0x00007ffff70ff9cd in arrow::engine::(anonymous namespace)::DeserializePlans (buf=..., declaration_factory=..., registry=0x5555559c9f80, ext_set_out=0x7fffffffd630, conversion_options=...)
    at /mnt/github/westonpace/arrow/cpp/src/arrow/engine/substrait/serde.cc:170
#14 0x00007ffff70ffee0 in arrow::engine::DeserializePlans(arrow::Buffer const&, std::function<std::shared_ptr<arrow::compute::SinkNodeConsumer> ()> const&, arrow::engine::ExtensionIdRegistry const*, arrow::engine::ExtensionSet*, arrow::engine::ConversionOptions const&) (buf=..., consumer_factory=..., registry=0x5555559c9f80, ext_set_out=0x7fffffffd630, conversion_options=...)
    at /mnt/github/westonpace/arrow/cpp/src/arrow/engine/substrait/serde.cc:199
#15 0x00005555556e7264 in arrow::engine::CheckRoundTripResult (output_schema=std::shared_ptr<arrow::Schema> (use count 2, weak count 0) = {...}, 
    expected_table=std::shared_ptr<arrow::Table> (use count 1, weak count 0) = {...}, exec_context=..., buf=std::shared_ptr<arrow::Buffer> (use count 1, weak count 0) = {...}, 
    include_columns=std::vector of length 0, capacity 0, conversion_options=...) at /mnt/github/westonpace/arrow/cpp/src/arrow/engine/substrait/serde_test.cc:191
#16 0x00005555557247d9 in arrow::engine::Substrait_AsOfJoinWithOutputMapping_Test::TestBody (this=0x5555558aeae0)
    at /mnt/github/westonpace/arrow/cpp/src/arrow/engine/substrait/serde_test.cc:4041
#17 0x00005555557be1df in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) ()
#18 0x00005555557b3686 in testing::Test::Run() ()
#19 0x00005555557b3805 in testing::TestInfo::Run() ()
#20 0x00005555557b3db9 in testing::TestSuite::Run() ()
#21 0x00005555557b44bf in testing::internal::UnitTestImpl::RunAllTests() ()
#22 0x00005555557be7a7 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) ()
#23 0x00005555557b38cc in testing::UnitTest::Run() ()
#24 0x000055555568eec4 in main ()
```

**Comment by rtpsw** [comment]
I marked this PR as a draft since we're now only using it to demonstrate that Ibis-Substrait's handling of output mapping should be fixed.

**Pull request closed without merging**
